---
title: "R You Ready to Learn R Socrata?"
author: "Justin, Ryan & Alicia"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Common Use Cases

- Ad-hoc interactive performance dashboards
- Internal report creation by non-technical users
- Joining open data with internal databases
- Reading and writing data from and to Socrata
- Exploratory analysis and visualizations and predictive modeling

## Why R and RStudio?

- R is free and open source language with an active community
- R makes it easy to create reproducible analysis documents as html, word, pdfs, slides and web shiny applications
- Lots of useful packages to make data analysis delightful
- RStudio is a robust and free tool that accelerates analysis for R

## Agenda

- [Read datasets from Socrata using RSocrata, readr and httr libraries](https://aliciatb.github.io/connect/read_data.html)
- Inspect dataset with summary statistics
- Exploratory analysis with the tidy verse
- Visualize dataset using ggplot
- Create a report in R markdown as a Word doc, PDF, and more!
- Create a flex dashboard that can be published to the web 

## Additional Resources

- [Socrata API Keys](https://socrataapikeys.docs.apiary.io/)
- [R Project](https://www.r-project.org/)
- [RStudio](https://www.rstudio.com/products/rstudio/download/)
- [RSocrata](https://github.com/Chicago/RSocrata)
- [R for Data Science](https://r4ds.had.co.nz/)
- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)